language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  - cp .env.travis .env
  - touch database/database.testing.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed

script:
- vendor/bin/phpunit